# Generated by Django 4.0 on 2022-03-17 20:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=home.models.create_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=1000)),
                ('published', models.DateTimeField(default=datetime.datetime(2022, 3, 17, 22, 44, 24, 960378))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
