# Generated by Django 4.0 on 2022-04-15 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_post_categories_alter_post_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 17, 51, 57, 373261)),
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together={('post', 'categorie')},
        ),
    ]
