# Generated by Django 4.0 on 2022-04-15 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_categories_id_alter_post_published_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 17, 57, 14, 856178)),
        ),
    ]
