# Generated by Django 4.0 on 2022-04-26 00:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_categories'),
        ('home', '0018_alter_post_published_humanconnections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 3, 22, 40, 726031)),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.CharField(default=home.models.create_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
