# Generated by Django 4.0 on 2022-03-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='C:\\Users\\ItayK\\Documents\\dev\\python\\cyber-senior-project\\locallibrary\\local_store\\profile_pics\\default.png', max_length=200),
        ),
    ]
